### PR TITLE
Added an overload to the Sample operator to take another observable t…

### PR DESCRIPTION
**Pull request by svermeulen**
…o use to determine the sample interval.  This is just a more generic version of SampleFrame.  To minimize duplication I also changed SampleFrame to be implemented based on this more generic version.

### CODE REVIEW

**Comment by neuecc** [comment]
In performance reason, Sample will be replaced optimized code #165 
so should not replace SampleFrameObservable to SampleObservableObseravble.

This is missing operator of Rx.NET `Sample<T, TSample>(IObservable<T> source, IObservable<TSample> sampler)`. #105
Yes, this is needed method, thank you!
But it should locate in Operators/Sample https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/Scripts/Operators/Sample.cs

**Comment by svermeulen** [comment]
Ok I'll submit it again with those changes.

**Comment by svermeulen** [comment]
Did I understand those changes correctly?

**Comment by neuecc** [comment]
Thank you!
almost okay.
I'll merge and fix after it.

**Pull request merged**
